server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
        - id: transactions
          uri: lb://transactions
          predicates:
            - Path=/transactions/**
        - id: statments
          uri: lb://statements
          predicates:
            - Path=/statements/**
